#!/usr/bin/python

# This script will read HC-12-USB data from the serial port
# and put it into a text file. Each device sending data will
# have its own text file.

from datetime import date
from datetime import datetime
import re
import serial

ser = serial.Serial('/dev/ttyUSB0', baudrate=9600)

while (1):
    ser_bytes = ser.readline()
    print ser_bytes,
