#!/usr/bin/python

# This script will read HC-12-USB data from the serial port
# and put it into a text file. Each device sending data will
# have its own text file.

from datetime import date
from datetime import datetime
import re
import serial
import sys
import os
import sqlite3
import sqlhelper as h
import filecheck as check

FILETYPE = ".db"

# Try and open serial port
# Exit function if serial port could not be opened
try:
    ser = serial.Serial('/dev/ttyUSB0', baudrate=9600)
except:
    print "Could not open Serial Port, restart script."
    sys.exit()

# Infinite loop for reading serial port
while (1):
    ser_bytes = ser.readline()
    decode_bytes = ser_bytes.decode("UTF-8")
    parse = re.split(r',', decode_bytes);
    parse[5] = parse[5].rstrip() #Remove \r and \n from string

    # Get date and time for timestamp of transmission
    today = date.today()
    curtime = datetime.now()
    d = today.strftime("%Y-%m-%d")
    t = curtime.strftime("%H:%M:%S")

    # Get device name and open file for specific device
    dev_name = parse[0]
    filename = dev_name + FILETYPE
    if (check.checkforfile(filename) == False):
	h.createdb(filename)
    
    # Format data to be inserted into SQL Database (Data as Tuple)
    data = (d,t,float(parse[1]),float(parse[2]),float(parse[3]),float(parse[4]),float(parse[5]))

    # Connect to SQL Database
    con = sqlite3.connect(filename)
    c = con.cursor()

    # Create table for data
    c.execute("INSERT INTO data VALUES (?,?,?,?,?,?,?);",data)

    # Close database
    con.commit()
    con.close()
