#!/usr/bin/python

# This script will read HC-12-USB data from the serial port
# and put it into a text file. Each device sending data will
# have its own text file.

from datetime import date
from datetime import datetime
import re
import serial
import sys

FILETYPE = ".txt"

# Try and open serial port
# Exit function if serial port could not be opened
try:
    ser = serial.Serial('/dev/ttyUSB0', baudrate=9600)
except:
    print "Could not open Serial Port, restart script."
    sys.exit()

# Infinite loop for reading serial port
while (1):
    ser_bytes = ser.readline()
    parse = re.split(r',', ser_bytes, maxsplit=1);
    dev_name = parse[0]
    filename = dev_name + FILETYPE
    f = open(filename, "a")
    f.write(parse[1])
    f.close()
    #print ser_bytes,
